<!DOCTYPE html>
<html><head>
<title><#Web_Title#> - 局域网自动发现</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<link rel="shortcut icon" href="images/favicon.ico"><link rel="icon" href="images/favicon.png">
<link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/bootstrap/css/main.css">
<link rel="stylesheet" type="text/css" href="/bootstrap/css/engage.itoggle.css">
<script type="text/javascript" src="/jquery.js"></script>
<script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/bootstrap/js/engage.itoggle.min.js"></script>
<script type="text/javascript" src="/state.js"></script>
<script type="text/javascript" src="/general.js"></script>
<script type="text/javascript" src="/itoggle.js"></script>
<script type="text/javascript" src="/popup.js"></script>
<script type="text/javascript">
var $j=jQuery.noConflict();
var rtimer=null, customIndex=0;
<% login_state_hook(); %>
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function norm(s){return String(s||'').replace(/&#10;/g,'\n').replace(/&#13;/g,'').replace(/\\n/g,'\n').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"');}
function section(t,a,b){var p=t.indexOf(a+'\n');if(p<0)return '';p+=a.length+1;var q=b?t.indexOf('\n'+b,p):-1;return norm(q<0?t.slice(p):t.slice(p,q)).replace(/^\n+|\n+$/g,'');}
function parseData(t){t=norm(t);var f=(t.split('\n')[0]||'').split('|');return {iface:f[1]||'-',role:f[2]||'-',ip:f[3]||'-',mac:f[4]||'-',link:f[5]||'-',dhcp:f[6]||'-',state:f[7]||'-',count:f[8]||'0',last:f[9]||'-',ifaces:section(t,'---IFACES---','---LOG---'),log:section(t,'---LOG---','---DEVICES---'),devices:section(t,'---DEVICES---','---CUSTOM---'),custom:section(t,'---CUSTOM---',null)};}
function ajaxData(cb){var x=new XMLHttpRequest();x.onreadystatechange=function(){if(x.readyState===4&&x.status===200)cb(x.responseText);};x.open('GET','Advanced_LANDiscover_Data.asp?_='+new Date().getTime(),true);x.send(null);}
function initToggles(){var a=['lan_discovery_enable','lan_discovery_dhcp_enable','lan_discovery_discover_enable','lan_discovery_onvif','lan_discovery_ssdp','lan_discovery_hik','lan_discovery_dahua','lan_discovery_raw'];for(var i=0;i<a.length;i++){try{init_itoggle(a[i]);}catch(e){}}}
function renderIfaces(s){var sel=document.getElementById('lan_ifname'),cur=sel.getAttribute('data-value')||sel.value||'',ls=norm(s).split('\n');sel.innerHTML='';for(var i=0;i<ls.length;i++){var l=ls[i].trim();if(!l)continue;var f=l.split('|');if(f.length<5)continue;var o=document.createElement('option');o.value=f[0];o.text=f[0]+' | '+f[1]+' | '+f[2]+' | '+f[4];if(f[0]===cur)o.selected=true;sel.appendChild(o);}if(!sel.value&&sel.options.length)sel.selectedIndex=0;}
function renderDevices(s){var b=document.getElementById('devices'),ls=norm(s).split('\n');b.innerHTML='';for(var i=0;i<ls.length;i++){var l=ls[i].trim();if(!l||l.indexOf('DEVICE ')!==0)continue;var typ=(l.match(/type=([^ ]+)/)||[])[1]||'-',ip=(l.match(/IP=([^ ]+)/)||[])[1]||'-',mac=(l.match(/MAC=([^ ]+)/)||[])[1]||'-',info=(l.match(/INFO=(.*)$/)||[])[1]||'-';var tr=document.createElement('tr');tr.innerHTML='<td>-</td><td>'+esc(typ)+'</td><td>'+esc(ip)+'</td><td>'+esc(mac)+'</td><td>'+esc(info)+'</td>';b.appendChild(tr);}if(!b.children.length)b.innerHTML='<tr><td colspan="5" class="muted">暂无设备</td></tr>';}
function renderCustom(s){var box=document.getElementById('custom_list');if(box.children.length)return;var ls=norm(s).split('\n');for(var i=0;i<ls.length;i++){var l=ls[i].trim();if(!l)continue;var f=l.split('|');if(f.length<5)continue;try{addCustomRow(decodeURIComponent(f[0]||''),decodeURIComponent(f[1]||''),decodeURIComponent(f[2]||''),decodeURIComponent(f[3]||''),f[4]);}catch(e){addCustomRow(f[0],f[1],f[2],f[3],f[4]);}}}
function addCustomRow(n,a,p,y,en){var id='lan_custom_'+(customIndex++),row=document.createElement('div'),on=String(en)==='1';row.className='well well-small custom-row';row.innerHTML='<div class="row-fluid"><div class="span2"><input class="span12 c-name" type="text" value="'+esc(n||'')+'" placeholder="名称"></div><div class="span3"><input class="span12 c-addr" type="text" value="'+esc(a||'')+'" placeholder="目标地址 / 组播地址"></div><div class="span1"><input class="span12 c-port" type="text" value="'+esc(p||'')+'" placeholder="UDP端口"></div><div class="span3"><input class="span12 c-payload" type="text" value="'+esc(y||'')+'" placeholder="Payload"></div><div class="span2"><div id="'+id+'_on_of"><input type="checkbox" id="'+id+'_fake" value="1" '+(on?'checked':'')+'><label class="itoggle" for="'+id+'_fake"></label></div><input type="radio" name="'+id+'_radio" id="'+id+'_0" value="0" style="display:none" '+(on?'':'checked')+'><input type="radio" name="'+id+'_radio" id="'+id+'_1" value="1" style="display:none" '+(on?'checked':'')+'><input type="hidden" class="c-enable" value="'+(on?'1':'0')+'"></div><div class="span1"><button type="button" class="btn btn-danger" onclick="this.parentNode.parentNode.parentNode.remove()">−</button></div></div>';document.getElementById('custom_list').appendChild(row);try{init_itoggle(id,function(){row.querySelector('.c-enable').value=$j('#'+id+'_fake:checked').length?'1':'0';});}catch(e){}}
function addCustom(){addCustomRow('','','','',1);}
function serializeCustom(){var rows=document.getElementById('custom_list').children,out=[];for(var i=0;i<rows.length;i++){var r=rows[i];out.push(encodeURIComponent(r.querySelector('.c-name').value)+'|'+encodeURIComponent(r.querySelector('.c-addr').value)+'|'+encodeURIComponent(r.querySelector('.c-port').value)+'|'+encodeURIComponent(r.querySelector('.c-payload').value)+'|'+(r.querySelector('.c-enable').value||'0'));}document.getElementById('lan_discovery_custom').value=out.join('\n');}
function refresh(){ajaxData(function(t){var o=parseData(t);renderIfaces(o.ifaces);document.getElementById('status_iface').innerHTML=esc(o.iface)+' ('+esc(o.role)+')';document.getElementById('status_ip').innerHTML=esc(o.ip);document.getElementById('status_mac').innerHTML=esc(o.mac);document.getElementById('status_link').innerHTML=esc(o.link);document.getElementById('status_dhcp').innerHTML=esc(o.dhcp);document.getElementById('status_state').innerHTML=esc(o.state);document.getElementById('status_count').innerHTML=esc(o.count);document.getElementById('status_last').innerHTML=esc(o.last);var lg=document.getElementById('live_log');lg.textContent=o.log||'暂无日志';lg.scrollTop=lg.scrollHeight;renderDevices(o.devices);renderCustom(o.custom);});}
function save(){if(!login_safe())return false;serializeCustom();showLoading();document.form.action_mode.value=' Apply ';document.form.current_page.value='/Advanced_LANDiscover_Content.asp';document.form.next_page.value='/Advanced_LANDiscover_Content.asp';document.form.submit();return false;}
function clearLog(){if(!login_safe())return false;document.getElementById('lan_discovery_log').value='';showLoading();document.form.action_mode.value=' Apply ';document.form.current_page.value='/Advanced_LANDiscover_Content.asp';document.form.next_page.value='/Advanced_LANDiscover_Content.asp';document.form.submit();return false;}
function initial(){show_banner(1);show_menu(8,0,0);show_footer();initToggles();refresh();if(rtimer)clearInterval(rtimer);rtimer=setInterval(refresh,1000);}
</script>
<style>
.custom-row{margin:6px 0;padding:8px}.custom-row input{margin-bottom:0}.status-table td{white-space:nowrap}.live-box{height:180px;overflow:auto;background:#111;color:#ddd;padding:8px;font-family:monospace;font-size:12px}.table th,.table td{vertical-align:middle}
</style></head>
<body onload="initial();" onunload="return unload_body();">
<div class="wrapper"><div class="container-fluid"><div class="row-fluid"><div class="span3"><center><div id="logo"></div></center></div><div class="span9"><div id="TopBanner"></div></div></div></div>
<div id="Loading" class="popup_bg"></div><iframe name="hidden_frame" id="hidden_frame" src="" width="0" height="0" frameborder="0"></iframe>
<form method="post" name="form" id="ruleForm" action="/start_apply.htm" target="hidden_frame">
<input type="hidden" name="current_page" value="Advanced_LANDiscover_Content.asp"><input type="hidden" name="next_page" value="Advanced_LANDiscover_Content.asp"><input type="hidden" name="action_mode" value=""><input type="hidden" name="action_script" value=""><input type="hidden" name="lan_discovery_log" id="lan_discovery_log" value=""><input type="hidden" name="lan_discovery_custom" id="lan_discovery_custom" value="<% nvram_get_x("", "lan_discovery_custom"); %>">
<div class="container-fluid"><div class="row-fluid"><div class="span3"><div class="well sidebar-nav side_nav" style="padding:0"><ul id="mainMenu" class="clearfix"></ul><ul class="clearfix"><li><div id="subMenu" class="accordion"></div></li></ul></div></div>
<div class="span9"><div class="box well grad_colour_dark_blue"><h2 class="box_head round_top">局域网自动发现</h2><div class="round_bottom"><div id="tabMenu" class="submenuBlock"></div>
<div class="alert alert-info">LAN事件 → DHCP检测 → 设备发现。自身地址自动过滤。</div>
<table class="table table-condensed status-table"><tr><th colspan="4">当前状态</th></tr><tr><td>检测接口</td><td id="status_iface">-</td><td>IPv4</td><td id="status_ip">-</td></tr><tr><td>MAC</td><td id="status_mac">-</td><td>Link</td><td id="status_link">-</td></tr><tr><td>DHCP</td><td id="status_dhcp">-</td><td>发现状态</td><td id="status_state">-</td></tr><tr><td>已发现</td><td id="status_count">0</td><td>最后活动</td><td id="status_last">-</td></tr></table>
<table class="table table-bordered"><tr><th style="width:180px">检测接口</th><td><select name="lan_discovery_ifname" id="lan_ifname" class="span9" data-value="<% nvram_get_x("", "lan_discovery_ifname"); %>"></select></td></tr>
<tr><th>LAN事件检测</th><td><div id="lan_discovery_enable_on_of"><input type="checkbox" id="lan_discovery_enable_fake" value="1" <% nvram_match_x("", "lan_discovery_enable", "1", "checked"); %>><label class="itoggle" for="lan_discovery_enable_fake"></label></div><input type="radio" name="lan_discovery_enable" id="lan_discovery_enable_0" value="0" style="display:none" <% nvram_match_x("", "lan_discovery_enable", "0", "checked"); %>><input type="radio" name="lan_discovery_enable" id="lan_discovery_enable_1" value="1" style="display:none" <% nvram_match_x("", "lan_discovery_enable", "1", "checked"); %>></td></tr>
<tr><th>DHCP检测</th><td><div id="lan_discovery_dhcp_enable_on_of"><input type="checkbox" id="lan_discovery_dhcp_enable_fake" value="1" <% nvram_match_x("", "lan_discovery_dhcp_enable", "1", "checked"); %>><label class="itoggle" for="lan_discovery_dhcp_enable_fake"></label></div><input type="radio" name="lan_discovery_dhcp_enable" id="lan_discovery_dhcp_enable_0" value="0" style="display:none" <% nvram_match_x("", "lan_discovery_dhcp_enable", "0", "checked"); %>><input type="radio" name="lan_discovery_dhcp_enable" id="lan_discovery_dhcp_enable_1" value="1" style="display:none" <% nvram_match_x("", "lan_discovery_dhcp_enable", "1", "checked"); %>> 超时 <input name="lan_discovery_dhcp_timeout" class="span1" value="<% nvram_get_x("", "lan_discovery_dhcp_timeout"); %>"></td></tr>
<tr><th>设备发现</th><td><div id="lan_discovery_discover_enable_on_of"><input type="checkbox" id="lan_discovery_discover_enable_fake" value="1" <% nvram_match_x("", "lan_discovery_discover_enable", "1", "checked"); %>><label class="itoggle" for="lan_discovery_discover_enable_fake"></label></div><input type="radio" name="lan_discovery_discover_enable" id="lan_discovery_discover_enable_0" value="0" style="display:none" <% nvram_match_x("", "lan_discovery_discover_enable", "0", "checked"); %>><input type="radio" name="lan_discovery_discover_enable" id="lan_discovery_discover_enable_1" value="1" style="display:none" <% nvram_match_x("", "lan_discovery_discover_enable", "1", "checked"); %>> 超时 <input name="lan_discovery_timeout" class="span1" value="<% nvram_get_x("", "lan_discovery_timeout"); %>"></td></tr>
<tr><th>ONVIF</th><td><div id="lan_discovery_onvif_on_of"><input type="checkbox" id="lan_discovery_onvif_fake" value="1" <% nvram_match_x("", "lan_discovery_onvif", "1", "checked"); %>><label class="itoggle" for="lan_discovery_onvif_fake"></label></div><input type="radio" name="lan_discovery_onvif" id="lan_discovery_onvif_0" value="0" style="display:none" <% nvram_match_x("", "lan_discovery_onvif", "0", "checked"); %>><input type="radio" name="lan_discovery_onvif" id="lan_discovery_onvif_1" value="1" style="display:none" <% nvram_match_x("", "lan_discovery_onvif", "1", "checked"); %>> 端口 <input name="lan_discovery_onvif_port" class="span2" value="<% nvram_get_x("", "lan_discovery_onvif_port"); %>"></td></tr>
<tr><th>SSDP</th><td><div id="lan_discovery_ssdp_on_of"><input type="checkbox" id="lan_discovery_ssdp_fake" value="1" <% nvram_match_x("", "lan_discovery_ssdp", "1", "checked"); %>><label class="itoggle" for="lan_discovery_ssdp_fake"></label></div><input type="radio" name="lan_discovery_ssdp" id="lan_discovery_ssdp_0" value="0" style="display:none" <% nvram_match_x("", "lan_discovery_ssdp", "0", "checked"); %>><input type="radio" name="lan_discovery_ssdp" id="lan_discovery_ssdp_1" value="1" style="display:none" <% nvram_match_x("", "lan_discovery_ssdp", "1", "checked"); %>> 端口 <input name="lan_discovery_ssdp_port" class="span2" value="<% nvram_get_x("", "lan_discovery_ssdp_port"); %>"></td></tr>
<tr><th>HIK-SADP</th><td><div id="lan_discovery_hik_on_of"><input type="checkbox" id="lan_discovery_hik_fake" value="1" <% nvram_match_x("", "lan_discovery_hik", "1", "checked"); %>><label class="itoggle" for="lan_discovery_hik_fake"></label></div><input type="radio" name="lan_discovery_hik" id="lan_discovery_hik_0" value="0" style="display:none" <% nvram_match_x("", "lan_discovery_hik", "0", "checked"); %>><input type="radio" name="lan_discovery_hik" id="lan_discovery_hik_1" value="1" style="display:none" <% nvram_match_x("", "lan_discovery_hik", "1", "checked"); %>> 端口 <input name="lan_discovery_hik_port" class="span2" value="<% nvram_get_x("", "lan_discovery_hik_port"); %>"></td></tr>
<tr><th>DAHUA-DHIP</th><td><div id="lan_discovery_dahua_on_of"><input type="checkbox" id="lan_discovery_dahua_fake" value="1" <% nvram_match_x("", "lan_discovery_dahua", "1", "checked"); %>><label class="itoggle" for="lan_discovery_dahua_fake"></label></div><input type="radio" name="lan_discovery_dahua" id="lan_discovery_dahua_0" value="0" style="display:none" <% nvram_match_x("", "lan_discovery_dahua", "0", "checked"); %>><input type="radio" name="lan_discovery_dahua" id="lan_discovery_dahua_1" value="1" style="display:none" <% nvram_match_x("", "lan_discovery_dahua", "1", "checked"); %>> 端口 <input name="lan_discovery_dahua_port" class="span2" value="<% nvram_get_x("", "lan_discovery_dahua_port"); %>"></td></tr>
<tr><th>ARP/IP</th><td><div id="lan_discovery_raw_on_of"><input type="checkbox" id="lan_discovery_raw_fake" value="1" <% nvram_match_x("", "lan_discovery_raw", "1", "checked"); %>><label class="itoggle" for="lan_discovery_raw_fake"></label></div><input type="radio" name="lan_discovery_raw" id="lan_discovery_raw_0" value="0" style="display:none" <% nvram_match_x("", "lan_discovery_raw", "0", "checked"); %>><input type="radio" name="lan_discovery_raw" id="lan_discovery_raw_1" value="1" style="display:none" <% nvram_match_x("", "lan_discovery_raw", "1", "checked"); %>></td></tr></table>
<div class="box well"><h4>已发现设备</h4><table class="table table-bordered table-condensed"><thead><tr><th>时间</th><th>协议</th><th>IP</th><th>MAC</th><th>信息</th></tr></thead><tbody id="devices"><tr><td colspan="5" class="muted">暂无设备</td></tr></tbody></table></div>
<div class="box well"><h4>实时发现日志 <button type="button" class="btn btn-mini pull-right" onclick="clearLog();return false;">清空</button></h4><div id="live_log" class="live-box">暂无日志</div></div>
<div class="box well"><h4>自定义 UDP 发现协议 <button type="button" class="btn btn-success btn-mini pull-right" onclick="addCustom();return false;">＋ 添加</button></h4><div class="muted" style="margin-bottom:8px">可无限添加。名称 / 目标地址 / UDP端口 / Payload / 开关 / 删除。</div><div id="custom_list"></div></div>
<div style="text-align:center;margin:15px 0"><button type="button" class="btn btn-primary" onclick="save();return false;">保存设置</button></div>
</div></div></div></div></div>
</form></div></body></html>
