<!DOCTYPE html>
<html>
<head>
<title><#Web_Title#> - 局域网自动发现</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<link rel="shortcut icon" href="images/favicon.ico">
<link rel="icon" href="images/favicon.png">
<link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/bootstrap/css/main.css">
<link rel="stylesheet" type="text/css" href="/bootstrap/css/engage.itoggle.css">
<script type="text/javascript" src="/jquery.js"></script>
<script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/bootstrap/js/engage.itoggle.min.js"></script>
<script type="text/javascript" src="/state.js"></script>
<script type="text/javascript" src="/general.js"></script>
<script type="text/javascript" src="/itoggle.js"></script>
<script type="text/javascript" src="/popup.js"></script>
<script type="text/javascript" src="/help.js"></script>
<script>
var $j=jQuery.noConflict();
var refresh_timer=null;
var custom_loaded=false;
var last_log_text='';
<% login_state_hook(); %>

function html_decode(v){
    var s=String(v==null?'':v);
    for(var i=0;i<5;i++){
        s=s.replace(/&amp;/gi,'&').replace(/&#38;/gi,'&')
         .replace(/&#10;/gi,'\n').replace(/&#13;/gi,'\n')
         .replace(/&#8232;/gi,'\n').replace(/&#x2028;/gi,'\n')
         .replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');
    }
    return s.replace(/\r/g,'');
}
function lines(v){return html_decode(v).split(/\n|\u2028/);}
function val(v,d){return(v!==undefined&&v!==null&&String(v)!==''&&String(v)!=='-')?String(v):d;}
function linkText(v){v=String(v||'');return v==='UP'?'已插入':(v==='DOWN'?'未插入':(v||'-'));}
function healthText(v){v=String(v||'');if(v==='OK')return'正常';if(v==='BROADCAST_STORM')return'广播风暴';if(v==='LOOP_SUSPECTED')return'疑似环路';if(v==='LOOP_BROADCAST')return'疑似环路/广播风暴';return v||'未监视';}
function macText(v){var m=String(v||'').replace(/\\/g,'').replace(/\s+/g,'').toUpperCase();return/^([0-9A-F]{2}:){5}[0-9A-F]{2}$/.test(m)?m:'-';}
function section(t,a,b){var p=t.indexOf(a);if(p<0)return'';p+=a.length;var q=b?t.indexOf(b,p):-1;return t.substring(p,q<0?t.length:q).replace(/^\n+|\n+$/g,'');}
function parseData(t){t=html_decode(t);var f=(t.split('\n')[0]||'').split('|');return{iface:val(f[1],'<% nvram_get_x("", "lan_discovery_ifname"); %>'),role:val(f[2],'LAN'),ip:val(f[3],'-'),mac:macText(val(f[4],'<% nvram_get_x("", "lan_hwaddr"); %>')),link:val(f[5],'-'),dhcp:val(f[6],'未检测'),state:val(f[7],'空闲'),count:val(f[8],'0'),last:val(f[9],'-'),health:val(f[10],'未监视'),broadcast:val(f[11],'0'),loop:val(f[12],'0'),ifaces:section(t,'---IFACES---','---LOG---'),log:section(t,'---LOG---','---DEVICES---'),devices:section(t,'---DEVICES---','---TARGETS---'),targets:section(t,'---TARGETS---','---CUSTOM---'),custom:section(t,'---CUSTOM---','')};}
function renderIfaces(s){var sel=document.getElementById('lan_ifname');if(!sel)return;var wanted='<% nvram_get_x("", "lan_discovery_ifname"); %>';var ls=lines(s),found=false;sel.innerHTML='';for(var i=0;i<ls.length;i++){var f=String(ls[i]||'').trim().split('|');if(f.length<5||!f[0]||f[1]!=='LAN'||/^(lo|br|ra|wds|apcli)/.test(f[0]))continue;var o=document.createElement('option');o.value=f[0];o.text=f[0]+' | '+f[1]+' | '+(f[2]||'-')+' | '+linkText(f[4]);if(f[0]===wanted){o.selected=true;found=true;}sel.appendChild(o);}if(!sel.options.length){var o=document.createElement('option');o.value=wanted||'eth2.1';o.text=(wanted||'eth2.1')+' | LAN';o.selected=true;sel.appendChild(o);}else if(!found){sel.selectedIndex=0;}}
function clean_device_info(v){var s=String(v||'');s=s.replace(/^Ping:\s*[^；]*；\s*/,'').replace(/\s*STATUS=[^ ]+/g,'').replace(/\s*PING=[^ ]+/g,'').replace(/\s*MISS=[0-9]+/g,'').replace(/^设备可达$/,'').replace(/^[；;、，,\s]+|[；;、，,\s]+$/g,'');return s||'-';}
function renderDevices(s){var b=document.getElementById('devices');if(!b)return;b.innerHTML='';var ls=lines(s),map={},order=[];for(var i=0;i<ls.length;i++){var z=String(ls[i]||'').trim();if(z.indexOf('DEVICE ')!==0||z.indexOf('type=SUBNET ')>=0)continue;var ip=(z.match(/IP=([^ ]+)/)||[])[1]||'-',type=(z.match(/type=([^ ]+)/)||[])[1]||'ARP',mac=(z.match(/MAC=([^ ]+)/)||[])[1]||'-',st=(z.match(/STATUS=([^ ]+)/)||[])[1]||'在线',ping=(z.match(/PING=([^ ]+)/)||[])[1]||'不可用',info=clean_device_info((z.match(/INFO=(.*)$/)||[])[1]||'-');if(!map[ip]){map[ip]={ip:ip,mac:mac,status:st,ping:ping,proto:[],info:[]};order.push(ip);}var d=map[ip];if(mac!=='-'&&d.mac==='-')d.mac=mac;if(st==='在线')d.status=st;if(ping==='通')d.ping=ping;if(type!=='ARP'&&d.proto.indexOf(type)<0)d.proto.push(type);if(info!=='-'&&d.info.indexOf(info)<0)d.info.push(info);}order.sort(function(a,b){return ipKey(a)-ipKey(b);});for(var j=0;j<order.length;j++){var d=map[order[j]],tr=document.createElement('tr');[d.status,d.proto.length?d.proto.join(' / '):'ARP',d.ip,macText(d.mac),d.ping,d.info.length?d.info.join('；'):'-'].forEach(function(v){var td=document.createElement('td');td.textContent=v;tr.appendChild(td);});b.appendChild(tr);}if(!order.length)b.innerHTML='<tr><td colspan="6" class="muted">暂无设备</td></tr>';}
function ipKey(ip){var p=String(ip||'').split('.');if(p.length!==4)return 4294967295;var n=0;for(var i=0;i<4;i++){if(!/^\d+$/.test(p[i]))return 4294967295;n=n*256+(+p[i]);}return n;}
function renderTargets(s){var b=document.getElementById('targets');if(!b)return;b.innerHTML='';var ls=String(s||'').split(';'),n=0;for(var i=0;i<ls.length;i++){var p=ls[i].split('|');if(p.length<2)continue;var tr=document.createElement('tr');[p[0],p[1],(p[2]||'已启用（SNAT）')].forEach(function(v){var td=document.createElement('td');td.textContent=v;tr.appendChild(td);});b.appendChild(tr);n++;}if(!n)b.innerHTML='<tr><td colspan="3" class="muted">等待目标网段状态...</td></tr>';}
function renderStatus(o){$j('#status_iface').text(o.iface);$j('#status_role').text(o.role);$j('#status_ip').text(o.ip);$j('#status_mac').text(o.mac);$j('#status_link').text(linkText(o.link));$j('#status_dhcp').text(o.dhcp);$j('#status_state').text(o.state);$j('#status_count').text(o.count);$j('#status_last').text(o.last);$j('#status_health').text(healthText(o.health));$j('#status_broadcast').text(o.broadcast+'/s');$j('#status_loop').text(o.loop+'/s');if(o.health==='OK'||o.health==='未监视'||o.health==='-')$j('#status_health').removeClass('health-danger');else $j('#status_health').addClass('health-danger');}
function refresh(){var x=new XMLHttpRequest();x.onreadystatechange=function(){if(x.readyState!==4||x.status!==200)return;var o=parseData(x.responseText);renderStatus(o);renderIfaces(o.ifaces);renderDevices(o.devices);renderTargets(o.targets);if(!custom_loaded){var ui=document.getElementById('lan_discovery_custom_ui');if(ui){ui.value=internalToUi(o.custom||'');custom_loaded=true;}}var lg=document.getElementById('live_log');var new_log=o.log||'暂无日志';if(lg&&new_log!==last_log_text){lg.textContent=new_log;lg.scrollTop=lg.scrollHeight;last_log_text=new_log;}};x.open('GET','Advanced_LANDiscover_Data.asp?_='+new Date().getTime(),true);x.send(null);}
function uiToInternal(t){var ls=lines(t),out=[];for(var i=0;i<ls.length;i++){var r=String(ls[i]||'').replace(/^\s+|\s+$/g,'');if(!r||r.charAt(0)==='#')continue;r=r.replace(/\s+#.*$/,'');var p=r.split(/\s+/);if(p.length<4)continue;var n=p[0].toLowerCase().replace(/_/g,'-'),port=p[2]||'-',en=p[p.length-1]==='0'?'0':'1';if(n==='onvif')out.push('onvif|'+port+'|'+en);else if(n==='ssdp')out.push('ssdp|'+port+'|'+en);else if(n==='hik'||n==='hik-sadp')out.push('hik-sadp|'+port+'|'+en);else if(n==='dahua'||n==='dahua-dhip')out.push('dahua-dhip|'+port+'|'+en);else if(n==='arp')out.push('arp|-|'+en);else out.push(encodeURIComponent(p[0])+'|'+encodeURIComponent(p[1]||'-')+'|'+encodeURIComponent(p[2]||'-')+'|'+encodeURIComponent(p.slice(3,p.length-1).join(' '))+'|'+en);}return out.join('\n');}
function internalToUi(t){var ls=lines(t),out=['# 协议    地址              端口    是否启用'],seen={onvif:0,ssdp:0,hik:0,dahua:0,arp:0};for(var i=0;i<ls.length;i++){var r=String(ls[i]||'').replace(/^\s+|\s+$/g,'');if(!r)continue;if(r.charAt(0)==='#'){if(r.indexOf('# 协议')!==0)out.push(r);continue;}var p=r.split('|'),n=(p[0]||'').toLowerCase().replace(/_/g,'-'),k=n==='hik-sadp'?'hik':(n==='dahua-dhip'?'dahua':n);if(k==='onvif'||k==='ssdp'||k==='hik'||k==='dahua'||k==='arp'){if(seen[k])continue;seen[k]=1;var addr=k==='dahua'?'239.255.255.251':(k==='arp'?'-':'239.255.255.250'),port={onvif:'3702',ssdp:'1900',hik:'37020',dahua:'37810',arp:'-'}[k];out.push(k+' '+addr+' '+(p[1]||port)+' '+(p[2]==='0'?'0':'1'));}else if(p.length>=5){out.push((p[0]||'custom')+' '+(p[1]||'-')+' '+(p[2]||'-')+' '+(p[4]==='0'?'0':'1')+'    # '+(p[3]||''));}}if(!seen.onvif)out.push('onvif 239.255.255.250 3702 1');if(!seen.ssdp)out.push('ssdp 239.255.255.250 1900 1');if(!seen.hik)out.push('hik 239.255.255.250 37020 1');if(!seen.dahua)out.push('dahua 239.255.255.251 37810 1');if(!seen.arp)out.push('arp - - 1');return out.join('\n');}
function applyRule(){if(!login_safe())return false;var ui=document.getElementById('lan_discovery_custom_ui'),hidden=document.getElementById('lan_discovery_custom');if(ui&&hidden)hidden.value=uiToInternal(ui.value);showLoading();document.form.action_mode.value=' Apply ';document.form.current_page.value='Advanced_LANDiscover_Content.asp';document.form.next_page.value='Advanced_LANDiscover_Content.asp';document.form.submit();return false;}
function clearLog(){if(!login_safe())return false;showLoading();document.form.action_mode.value=' Update ';document.form.action_script.value='lan_discovery_clear_log';document.form.current_page.value='Advanced_LANDiscover_Content.asp';document.form.next_page.value='Advanced_LANDiscover_Content.asp';document.form.submit();return false;}
function clearDevices(){if(!login_safe())return false;showLoading();document.form.action_mode.value=' Update ';document.form.action_script.value='lan_discovery_clear_devices';document.form.current_page.value='Advanced_LANDiscover_Content.asp';document.form.next_page.value='Advanced_LANDiscover_Content.asp';document.form.submit();return false;}
function initial(){show_banner(1);show_menu(5,3,1);show_footer();init_itoggle('lan_discovery_enable');init_itoggle('lan_discovery_dhcp_enable');init_itoggle('lan_discovery_discover_enable');var f=document.form;if(!f.lan_discovery_dhcp_timeout.value)f.lan_discovery_dhcp_timeout.value='3';if(!f.lan_discovery_cycle.value)f.lan_discovery_cycle.value='10';if(!f.lan_discovery_sweep_cycle.value)f.lan_discovery_sweep_cycle.value='120';if(!f.lan_discovery_miss_limit.value)f.lan_discovery_miss_limit.value='3';refresh();if(refresh_timer)clearInterval(refresh_timer);refresh_timer=setInterval(refresh,3000);}
</script>
<style type="text/css">
.status-table td{white-space:nowrap;vertical-align:middle}.mini{width:55px;margin:0 3px}.health-danger{font-weight:bold;color:#b94a48}.live-box{height:220px;overflow:auto;background:#111;color:#ddd;padding:8px;font:12px/1.55 monospace;white-space:pre-wrap}.custom-area{width:100%;min-height:210px;box-sizing:border-box;font:13px/1.55 monospace;white-space:pre}.note{color:#888}.target-table td,.target-table th{white-space:nowrap;vertical-align:middle}.hidden-builtin{position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden}
</style>
</head>
<body onload="initial();" onunload="return unload_body();">
<div class="wrapper">
<div class="container-fluid" style="padding-right:0"><div class="row-fluid"><div class="span3"><center><div id="logo"></div></center></div><div class="span9"><div id="TopBanner"></div></div></div></div>
<div id="Loading" class="popup_bg"></div><iframe name="hidden_frame" id="hidden_frame" width="0" height="0" frameborder="0"></iframe>
<form method="post" name="form" action="/start_apply.htm" target="hidden_frame">
<input type="hidden" name="current_page" value="Advanced_LANDiscover_Content.asp"><input type="hidden" name="next_page" value=""><input type="hidden" name="next_host" value=""><input type="hidden" name="sid_list" value="LANHostConfig;"><input type="hidden" name="group_id" value=""><input type="hidden" name="action_mode" value=""><input type="hidden" name="action_script" value=""><input type="hidden" name="lan_discovery_custom" id="lan_discovery_custom" value="">
<div class="container-fluid"><div class="row-fluid"><div class="span3"><div class="well sidebar-nav side_nav" style="padding:0"><ul id="mainMenu" class="clearfix"></ul><ul class="clearfix"><li><div id="subMenu" class="accordion"></div></li></ul></div></div>
<div class="span9"><div class="box well grad_colour_dark_blue"><h2 class="box_head round_top">LAN监听与设备发现</h2><div class="round_bottom"><div id="tabMenu" class="submenuBlock"></div>
<div class="alert alert-info">LAN口插拔、DHCP、ARP、协议发现和网络健康状态由后台运行。本页面只负责配置与显示，不改变后台发现逻辑。</div>
<table class="table table-condensed status-table"><tr><th colspan="8">当前状态</th></tr><tr><td>检测接口</td><td id="status_iface">-</td><td>LAN IPv4</td><td id="status_ip">-</td><td>LAN口</td><td id="status_link">-</td><td>DHCP</td><td id="status_dhcp">-</td></tr><tr><td>发现状态</td><td id="status_state">-</td><td>已发现</td><td id="status_count">0</td><td>最后活动</td><td id="status_last">-</td><td>MAC</td><td id="status_mac">-</td></tr><tr><td>网络健康</td><td id="status_health">未监视</td><td>广播速率</td><td id="status_broadcast">0/s</td><td>MAC回流</td><td id="status_loop">0/s</td><td>说明</td><td>红色=异常</td></tr></table>
<table class="table table-bordered table-condensed"><tr><th width="190">检测接口</th><td><select name="lan_discovery_ifname" id="lan_ifname" class="span9"><option value="<% nvram_get_x("", "lan_discovery_ifname"); %>"><% nvram_get_x("", "lan_discovery_ifname"); %> | LAN</option></select></td></tr>
<tr><th>LAN事件检测</th><td><div class="main_itoggle"><div id="lan_discovery_enable_on_of"><input type="checkbox" id="lan_discovery_enable_fake" <% nvram_match_x("", "lan_discovery_enable", "1", "checked"); %>></div></div><div class="hidden-builtin"><input type="radio" id="lan_discovery_enable_1" name="lan_discovery_enable" value="1" <% nvram_match_x("", "lan_discovery_enable", "1", "checked"); %>><input type="radio" id="lan_discovery_enable_0" name="lan_discovery_enable" value="0" <% nvram_match_x("", "lan_discovery_enable", "0", "checked"); %>></div><span class="note">监视LAN插拔并驱动后台发现服务</span></td></tr>
<tr><th>DHCP检测</th><td><div class="main_itoggle"><div id="lan_discovery_dhcp_enable_on_of"><input type="checkbox" id="lan_discovery_dhcp_enable_fake" <% nvram_match_x("", "lan_discovery_dhcp_enable", "1", "checked"); %>></div></div><div class="hidden-builtin"><input type="radio" id="lan_discovery_dhcp_enable_1" name="lan_discovery_dhcp_enable" value="1" <% nvram_match_x("", "lan_discovery_dhcp_enable", "1", "checked"); %>><input type="radio" id="lan_discovery_dhcp_enable_0" name="lan_discovery_dhcp_enable" value="0" <% nvram_match_x("", "lan_discovery_dhcp_enable", "0", "checked"); %>></div><input class="mini" name="lan_discovery_dhcp_timeout" onkeypress="return is_number(this,event);" value="<% nvram_get_x("", "lan_discovery_dhcp_timeout"); %>"> 秒</td></tr>
<tr><th>设备发现</th><td><div class="main_itoggle"><div id="lan_discovery_discover_enable_on_of"><input type="checkbox" id="lan_discovery_discover_enable_fake" <% nvram_match_x("", "lan_discovery_discover_enable", "1", "checked"); %>></div></div><div class="hidden-builtin"><input type="radio" id="lan_discovery_discover_enable_1" name="lan_discovery_discover_enable" value="1" <% nvram_match_x("", "lan_discovery_discover_enable", "1", "checked"); %>><input type="radio" id="lan_discovery_discover_enable_0" name="lan_discovery_discover_enable" value="0" <% nvram_match_x("", "lan_discovery_discover_enable", "0", "checked"); %>></div><span class="note">启用后持续周期探测和实时监听</span></td></tr>
<tr><th>主动探测单次窗口</th><td><input class="mini" name="lan_discovery_cycle" onkeypress="return is_number(this,event);" value="<% nvram_get_x("", "lan_discovery_cycle"); %>"> 秒 <span class="note">仅在主动补漏时使用；实时tcpdump持续监听，不受此值影响</span></td></tr>
<tr><th>主动补漏周期</th><td><input class="mini" name="lan_discovery_sweep_cycle" onkeypress="return is_number(this,event);" value="<% nvram_get_x("", "lan_discovery_sweep_cycle"); %>"> 秒 <span class="note">ARP和ONVIF/SSDP/海康/大华主动探测仅在此周期执行，默认120秒</span></td></tr>
<tr><th>目标网段丢失轮数</th><td><input class="mini" name="lan_discovery_miss_limit" onkeypress="return is_number(this,event);" value="<% nvram_get_x("", "lan_discovery_miss_limit"); %>"> 轮 <span class="note">连续完整扫描达到此轮数后才清理目标网段</span></td></tr>
<tr><th>LAN拔出处理</th><td><b>始终保留</b> <span class="note">拔出LAN只暂停实时监听和周期发现，不清除已有目标网段、临时IP和SNAT。</span></td></tr></table>
<h4>自定义探测配置</h4><div class="alert alert-info">格式：<b>协议 地址 端口 是否启用</b>。示例：onvif 239.255.255.250 3702 1；ARP填写：arp - - 1。</div>
<textarea id="lan_discovery_custom_ui" class="custom-area" rows="9"></textarea>
<h4>目标网段与临时IP</h4><table class="table table-bordered table-condensed target-table"><thead><tr><th>目标网段</th><th>临时IP（SNAT地址）</th><th>状态</th></tr></thead><tbody id="targets"><tr><td colspan="3" class="muted">等待目标网段状态...</td></tr></tbody></table>
<h4>已发现设备 <button type="button" class="btn btn-mini pull-right" onclick="clearDevices();return false;">清空设备</button></h4><table class="table table-bordered table-condensed"><thead><tr><th>状态</th><th>协议</th><th>IP</th><th>MAC</th><th>Ping</th><th>信息</th></tr></thead><tbody id="devices"><tr><td colspan="6" class="muted">暂无设备</td></tr></tbody></table>
<h4>实时监听日志 <button type="button" class="btn btn-mini pull-right" onclick="clearLog();return false;">清空日志</button></h4><pre id="live_log" class="live-box">暂无日志</pre>
<table class="table"><tr><td style="border:0"><center><input class="btn btn-primary" style="width:219px" type="button" value="保存" onclick="applyRule();return false;"></center></td></tr></table>
</div></div></div></div></div></form><div id="footer"></div></div>
</body>
</html>
