<!DOCTYPE html>
<html><head>
<title><#Web_Title#> - 局域网发现</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="shortcut icon" href="images/favicon.ico"><link rel="icon" href="images/favicon.png">
<link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/bootstrap/css/main.css">
<script type="text/javascript" src="/jquery.js"></script><script type="text/javascript" src="/state.js"></script><script type="text/javascript" src="/popup.js"></script>
<script type="text/javascript">
var $j=jQuery.noConflict();<% login_state_hook(); %>;
var rtimer, ci=0;
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');}
function initSwitches(){var a=document.getElementsByClassName('lan-switch');for(var i=0;i<a.length;i++){var h=a[i].nextElementSibling;var on=h&&h.value==='1';a[i].innerHTML=on?'启用':'禁用';a[i].className=on?'btn btn-success':'btn btn-default';a[i].className+=' btn-mini';}}
function sw(b){var h=b.nextElementSibling,on=h.value==='1';h.value=on?'0':'1';b.innerHTML=on?'禁用':'启用';b.className=on?'btn btn-default btn-mini':'btn btn-success btn-mini';}
function ajaxData(cb){var x=new XMLHttpRequest();x.onreadystatechange=function(){if(x.readyState===4&&x.status===200)cb(x.responseText);};x.open('GET','Advanced_LANDiscover_Data.asp?_='+new Date().getTime(),true);x.send(null);}
function parseData(t){var p=t.split('---DEVICES---'),a=p[0].split('\n'),d=(p[1]||'').split('---CUSTOM---'),c=(d[1]||'').trim();return {ifname:a[0]||'-',role:a[1]||'-',ip:a[2]||'-',mac:a[3]||'-',link:a[4]||'-',dhcp:a[5]||'-',state:a[6]||'-',count:a[7]||'0',last:a[8]||'-',interfaces:a[9]||'',log:(a.slice(10).join('\n')||''),devices:(d[0]||'').trim(),custom:c};}
function renderIfaces(s){var sel=document.getElementById('lan_ifname'),cur=sel.value||sel.getAttribute('data-value')||'',lines=s.split('\\n'),i,f,o;sel.innerHTML='';for(i=0;i<lines.length;i++){if(!lines[i])continue;f=lines[i].split('|');if(f.length<5)continue;o=document.createElement('option');o.value=f[0];o.text=f[0]+' | '+f[1]+' | '+f[2]+' | '+f[4];if(f[0]===cur)o.selected=true;sel.appendChild(o);}if(!sel.value&&sel.options.length)sel.selectedIndex=0;}
function refresh(){ajaxData(function(t){var o=parseData(t);renderIfaces(o.interfaces);document.getElementById('status_iface').innerHTML=esc(o.ifname)+' ('+esc(o.role)+')';document.getElementById('status_ip').innerHTML=esc(o.ip);document.getElementById('status_mac').innerHTML=esc(o.mac);document.getElementById('status_link').innerHTML=esc(o.link);document.getElementById('status_dhcp').innerHTML=esc(o.dhcp);document.getElementById('status_state').innerHTML=esc(o.state);document.getElementById('status_count').innerHTML=esc(o.count);document.getElementById('status_last').innerHTML=esc(o.last);var lg=document.getElementById('live_log');lg.textContent=o.log||'暂无日志';lg.scrollTop=lg.scrollHeight;renderDevices(o.devices);if(!document.getElementById('custom_list').children.length&&o.custom)renderCustom(o.custom);});}
function renderDevices(s){var body=document.getElementById('devices');body.innerHTML='';var lines=s.split('\n'),i,l,m,ip,mac,info,typ;for(i=0;i<lines.length;i++){l=lines[i].trim();if(!l||l.indexOf('DEVICE ')!==0)continue;typ=(l.match(/type=([^ ]+)/)||[])[1]||'-';ip=(l.match(/IP=([^ ]+)/)||[])[1]||'-';mac=(l.match(/MAC=([^ ]+)/)||[])[1]||'-';info=(l.match(/INFO=(.*)$/)||[])[1]||'-';m=document.createElement('tr');m.innerHTML='<td>-</td><td>'+esc(typ)+'</td><td>'+esc(ip)+'</td><td>'+esc(mac)+'</td><td>'+esc(info)+'</td>';body.appendChild(m);}if(!body.children.length)body.innerHTML='<tr><td colspan="5">暂无设备</td></tr>';}
function clearLog(){document.getElementById('lan_discovery_log').value='';save();}
function addCustomRow(n,a,p,y,e){var i=ci++,d=document.createElement('div');d.className='well well-small custom-row';d.innerHTML='<div class="row-fluid"><div class="span2"><input class="span12 c-name" value="'+esc(n||'')+'" placeholder="名称"></div><div class="span3"><input class="span12 c-addr" value="'+esc(a||'')+'" placeholder="目标地址/组播地址"></div><div class="span1"><input class="span12 c-port" value="'+esc(p||'')+'" placeholder="UDP端口"></div><div class="span4"><input class="span12 c-payload" value="'+esc(y||'')+'" placeholder="Payload"></div><div class="span1"><button type="button" class="btn lan-switch" onclick="sw(this)">启用</button><input class="c-enable" type="hidden" value="'+((e||'1')==='1'?'1':'0')+'"></div><div class="span1"><button type="button" class="btn btn-danger btn-mini" onclick="this.parentNode.parentNode.parentNode.remove()">−</button></div></div>';document.getElementById('custom_list').appendChild(d);initSwitches();}
function renderCustom(s){document.getElementById('custom_list').innerHTML='';ci=0;if(!s)return;var rows=s.split('\n');for(var i=0;i<rows.length;i++){if(!rows[i])continue;var f=rows[i].split('|');if(f.length<5)continue;addCustomRow(decodeURIComponent(f[0]||''),decodeURIComponent(f[1]||''),decodeURIComponent(f[2]||''),decodeURIComponent(f[3]||''),f[4]);}}
function addCustom(){addCustomRow('','','','', '1');}
function serializeCustom(){var rows=document.getElementById('custom_list').children,out=[];for(var i=0;i<rows.length;i++){var r=rows[i];out.push(encodeURIComponent(r.querySelector('.c-name').value)+'|'+encodeURIComponent(r.querySelector('.c-addr').value)+'|'+encodeURIComponent(r.querySelector('.c-port').value)+'|'+encodeURIComponent(r.querySelector('.c-payload').value)+'|'+r.querySelector('.c-enable').value);}document.getElementById('lan_discovery_custom').value=out.join('\n');}
function save(){if(!login_safe())return false;serializeCustom();document.form.action_mode.value=' Apply ';document.form.current_page.value='Advanced_LANDiscover_Content.asp';document.form.next_page.value='Advanced_LANDiscover_Content.asp';document.form.submit();}
function initial(){show_banner(1);show_menu(8,0,0);show_footer();initSwitches();refresh();rtimer=setInterval(refresh,1000);}
</script></head>
<body onLoad="initial();"><div class="wrapper"><div class="container-fluid"><div class="row-fluid"><div class="span3"><center><div id="logo"></div></center></div><div class="span9"><div id="TopBanner"></div></div></div></div><div id="Loading" class="popup_bg"></div><iframe name="hidden_frame" id="hidden_frame" src="" width="0" height="0" frameborder="0"></iframe>
<form method="post" name="form" action="apply.cgi"><input type="hidden" name="current_page"><input type="hidden" name="next_page"><input type="hidden" name="action_mode"><input type="hidden" name="action_script"><input type="hidden" name="lan_discovery_custom" id="lan_discovery_custom" value="<% nvram_get_x("", "lan_discovery_custom"); %>"><input type="hidden" name="lan_discovery_log" id="lan_discovery_log" value="">
<div class="container-fluid"><div class="row-fluid"><div class="span3"><div class="well sidebar-nav side_nav" style="padding:0"><ul id="mainMenu" class="clearfix"></ul><ul><li><div id="subMenu" class="accordion"></div></li></ul></div></div><div class="span9"><div class="box well grad_colour_dark_blue"><h2 class="box_head round_top">局域网自动发现</h2><div class="round_bottom"><div id="tabMenu" class="submenuBlock"></div>
<div class="alert alert-info">LAN事件 → DHCP检测 → 设备发现。自身地址自动过滤。</div>
<table class="table table-condensed"><tr><th colspan="4">当前状态</th></tr><tr><td>检测接口</td><td id="status_iface">-</td><td>IPv4</td><td id="status_ip">-</td></tr><tr><td>MAC</td><td id="status_mac">-</td><td>Link</td><td id="status_link">-</td></tr><tr><td>DHCP</td><td id="status_dhcp">-</td><td>发现状态</td><td id="status_state">-</td></tr><tr><td>已发现</td><td id="status_count">0</td><td>最后活动</td><td id="status_last">-</td></tr></table>
<table class="table"><tr><th style="width:180px">检测接口</th><td><select name="lan_discovery_ifname" id="lan_ifname" class="span9" data-value="<% nvram_get_x("", "lan_discovery_ifname"); %>"></select></td></tr>
<tr><td>LAN事件检测</td><td><button type="button" class="btn lan-switch" onclick="sw(this)">启用</button><input type="hidden" name="lan_discovery_enable" value="<% nvram_get_x("", "lan_discovery_enable"); %>"></td></tr>
<tr><td>DHCP检测</td><td><button type="button" class="btn lan-switch" onclick="sw(this)">启用</button><input type="hidden" name="lan_discovery_dhcp_enable" value="<% nvram_get_x("", "lan_discovery_dhcp_enable"); %>"> 超时 <input name="lan_discovery_dhcp_timeout" class="span2" value="<% nvram_get_x("", "lan_discovery_dhcp_timeout"); %>"></td></tr>
<tr><td>设备发现</td><td><button type="button" class="btn lan-switch" onclick="sw(this)">启用</button><input type="hidden" name="lan_discovery_discover_enable" value="<% nvram_get_x("", "lan_discovery_discover_enable"); %>"> 超时 <input name="lan_discovery_timeout" class="span2" value="<% nvram_get_x("", "lan_discovery_timeout"); %>"></td></tr>
<tr><td>ONVIF</td><td><button type="button" class="btn lan-switch" onclick="sw(this)">启用</button><input type="hidden" name="lan_discovery_onvif" value="<% nvram_get_x("", "lan_discovery_onvif"); %>"> 端口 <input name="lan_discovery_onvif_port" class="span2" value="<% nvram_get_x("", "lan_discovery_onvif_port"); %>"></td></tr>
<tr><td>SSDP</td><td><button type="button" class="btn lan-switch" onclick="sw(this)">启用</button><input type="hidden" name="lan_discovery_ssdp" value="<% nvram_get_x("", "lan_discovery_ssdp"); %>"> 端口 <input name="lan_discovery_ssdp_port" class="span2" value="<% nvram_get_x("", "lan_discovery_ssdp_port"); %>"></td></tr>
<tr><td>HIK-SADP</td><td><button type="button" class="btn lan-switch" onclick="sw(this)">启用</button><input type="hidden" name="lan_discovery_hik" value="<% nvram_get_x("", "lan_discovery_hik"); %>"> 端口 <input name="lan_discovery_hik_port" class="span2" value="<% nvram_get_x("", "lan_discovery_hik_port"); %>"></td></tr>
<tr><td>DAHUA-DHIP</td><td><button type="button" class="btn lan-switch" onclick="sw(this)">启用</button><input type="hidden" name="lan_discovery_dahua" value="<% nvram_get_x("", "lan_discovery_dahua"); %>"> 端口 <input name="lan_discovery_dahua_port" class="span2" value="<% nvram_get_x("", "lan_discovery_dahua_port"); %>"></td></tr>
<tr><td>ARP/IP</td><td><button type="button" class="btn lan-switch" onclick="sw(this)">启用</button><input type="hidden" name="lan_discovery_raw" value="<% nvram_get_x("", "lan_discovery_raw"); %>"></td></tr></table>
<div class="box"><h4>已发现设备</h4><table class="table table-striped"><thead><tr><th>时间</th><th>协议</th><th>IP</th><th>MAC</th><th>信息</th></tr></thead><tbody id="devices"><tr><td colspan="5">暂无设备</td></tr></tbody></table></div>
<div class="box"><h4>实时发现日志 <button type="button" class="btn btn-mini pull-right" onclick="clearLog()">清空</button></h4><pre id="live_log" style="height:220px;overflow:auto;margin:0">加载中...</pre></div>
<div class="box"><h4>自定义 UDP 发现协议 <button type="button" class="btn btn-success btn-mini pull-right" onclick="addCustom()">＋ 添加</button></h4><div class="muted">名称 / 目标地址 / UDP端口 / Payload / 开关 / 删除，不限制 6 条。</div><div id="custom_list"></div><div style="margin-top:10px"><button type="button" class="btn btn-primary" onclick="save()">保存设置</button></div></div>
</div></div></div></div></div></div></form><div id="footer"></div></div></body></html>
