#!/bin/bash

if [ -z "$1" ] ; then
	echo "Usage: $0 PRODUCT_NAME"
	echo "See 'configs/templates/' for available product names"
	exit 1
fi

if [ ! -f configs/templates/$1.config ] ; then
	echo "configs/templates/$1.config not found!"
	exit 1
fi

cp -f configs/templates/$1.config .config

ROOTDIR=`pwd`
export ROOTDIR=$ROOTDIR

kernel_id="3.4.x"
kernel_tf=""
busybox_id="1.24.x"
busybox_cf="$ROOTDIR/configs/boards/busybox.config"
busybox_tf="$ROOTDIR/user/busybox/busybox-${busybox_id}/.config"
board_h=""
board_mk=""

func_enable_kernel_param()
{
	if [ -n "`grep \"^# $1 is not set\" $kernel_tf`" ] ; then
		sed -i "s/# $1 is not set/$1=y/" $kernel_tf
	fi
}

func_disable_kernel_param()
{
	if [ -n "`grep \"^$1=y\" $kernel_tf`" ] ; then
		sed -i "s/$1=y/# $1 is not set/" $kernel_tf
	elif [ -n "`grep \"^$1=m\" $kernel_tf`" ] ; then
		sed -i "s/$1=m/# $1 is not set/" $kernel_tf
	fi
}

func_enable_busybox_param()
{
	if [ -n "`grep \"^# $1 is not set\" $busybox_tf`" ] ; then
		sed -i "s/# $1 is not set/$1=y/" $busybox_tf
	fi
}

func_disable_busybox_param()
{
	if [ -n "`grep \"^$1=y\" $busybox_tf`" ] ; then
		sed -i "s/$1=y/# $1 is not set/" $busybox_tf
	fi
}

. $ROOTDIR/toolchain.inc
echo "CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}" >> .config

. $ROOTDIR/.config

if [ ! -f "$ROOTDIR/vendors/Ralink/config.arch" ] ; then
	echo "Project product dir not found! Terminate."
	exit 1
fi

if [ ! -d "$ROOTDIR/$CONFIG_LINUXDIR" ] ; then
	echo "Project Linux Kernel dir ($CONFIG_LINUXDIR) not found! Terminate."
	exit 1
fi

board_h="$ROOTDIR/configs/boards/$CONFIG_FIRMWARE_PRODUCT_ID/board.h"
board_mk="$ROOTDIR/configs/boards/$CONFIG_FIRMWARE_PRODUCT_ID/board.mk"
kernel_cd="$ROOTDIR/configs/boards/$CONFIG_FIRMWARE_PRODUCT_ID"
kernel_tf="$ROOTDIR/$CONFIG_LINUXDIR/.config"

if [ "$CONFIG_FIRMWARE_TYPE_ROOTFS_IN_RAM" = "y" ] ; then
	kernel_cf="${kernel_cd}/kernel-${kernel_id}.ram.config"
elif [ -n "$CONFIG_FIRMWARE_KERNEL_CONFIG" ]; then
	kernel_cf="${kernel_cd}/$CONFIG_FIRMWARE_KERNEL_CONFIG"
else
	kernel_cf="${kernel_cd}/kernel-${kernel_id}.config"
fi

if [ ! -f "$kernel_cf" ] ; then
	echo "Target kernel config ($kernel_cf) not found! Terminate."
	exit 1
fi

if [ ! -f "$busybox_cf" ] ; then
	echo "Target BusyBox config ($busybox_cf) not found! Terminate."
	exit 1
fi

if [ ! -f "$board_h" ] ; then
	echo "Target board header ($board_h) not found! Terminate."
	exit 1
fi

if [ ! -f "$board_mk" ] ; then
	echo "Target board descriptor ($board_mk) not found! Terminate."
	exit 1
fi

rm -rf $ROOTDIR/romfs
rm -rf $ROOTDIR/images
mkdir -p $ROOTDIR/romfs
mkdir -p $ROOTDIR/images

. "$kernel_cf"

echo "--------------------------COPY-CONFIG-----------------------------"
echo "######################### FOR-ALL-DEVICES #############################"
ln -sf vendors/Ralink/config.arch config.arch
cp -fL "$kernel_cf" "$kernel_tf"
# Linux 3.4.x in this tree can see newer Kconfig symbols during CI.
# Keep this newly introduced conntrack option disabled before any
# silentoldconfig/oldconfig step so non-interactive builds never prompt.
if grep -q '^CONFIG_NETFILTER_CONNTRACK_CHAIN_EVENTS=' "$kernel_tf"; then
	sed -i 's/^CONFIG_NETFILTER_CONNTRACK_CHAIN_EVENTS=.*/# CONFIG_NETFILTER_CONNTRACK_CHAIN_EVENTS is not set/' "$kernel_tf"
elif ! grep -q '^# CONFIG_NETFILTER_CONNTRACK_CHAIN_EVENTS is not set' "$kernel_tf"; then
	printf '\n# CONFIG_NETFILTER_CONNTRACK_CHAIN_EVENTS is not set\n' >> "$kernel_tf"
fi
cp -fL "$busybox_cf" "$busybox_tf"
cp -fL "$board_mk" "$ROOTDIR/user/shared/board.mk"
cp -fL "$board_h" "$ROOTDIR/user/shared/include/ralink_board.h"
echo "############################# WI-FI ###################################"
dir_wifi_src="$ROOTDIR/proprietary/rt_wifi"
dir_wifi_dst="$ROOTDIR/$CONFIG_LINUXDIR/drivers/net/wireless/ralink"
dir_wifi_ver="2.7.X.X"
rm -rf "$dir_wifi_dst/rt2860v2"
rm -rf "$dir_wifi_dst/rt3090"
rm -rf "$dir_wifi_dst/rt5392"
rm -rf "$dir_wifi_dst/rt5592"
rm -rf "$dir_wifi_dst/rt3593"
rm -rf "$dir_wifi_dst/mt7610"
rm -rf "$dir_wifi_dst/mt76x2"
rm -rf "$dir_wifi_dst/mt76x3"
rm -rf "$dir_wifi_dst/mt7628"
rm -rf "$dir_wifi_dst/mt7615"
rm -rf "$dir_wifi_dst/mt7915"

mkdir -p "$dir_wifi_dst/mt76x3"
cp -f "$dir_wifi_src/rtpci/4.1.X.X/mt76x3/Kconfig" "$dir_wifi_dst/mt76x3/Kconfig"
mkdir -p "$dir_wifi_dst/mt7615/embedded"
cp -f "$dir_wifi_src/rtpci/5.0.5.1/mt7615/embedded/Kconfig" "$dir_wifi_dst/mt7615/embedded/Kconfig"
mkdir -p "$dir_wifi_dst/mt7915/embedded"
cp -f "$dir_wifi_src/rtpci/7.3.0.1/mt7915/embedded/Kconfig" "$dir_wifi_dst/mt7915/embedded/Kconfig"

if [ "$CONFIG_RALINK_MT7620" = "y" ] ; then
	if [ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "3.0" ] && [ -n "$CONFIG_MT76X2_AP" ] ; then
		func_disable_kernel_param "CONFIG_RT_FIRST_IF_RT2860"
		func_enable_kernel_param "CONFIG_RT_FIRST_IF_MT7620"
		CONFIG_RT_FIRST_IF_RT2860=""
	else
		func_enable_kernel_param "CONFIG_RT_FIRST_IF_RT2860"
		func_disable_kernel_param "CONFIG_RT_FIRST_IF_MT7620"
		CONFIG_RT_FIRST_IF_RT2860=y
	fi
	if [ -n "$CONFIG_RT_FIRST_IF_RT2860" = "y" ] ; then
		cp -rfL "$dir_wifi_src/rtsoc/$dir_wifi_ver/rt2860v2" "$dir_wifi_dst/"
		cp -rfL "$dir_wifi_src/rtsoc/$dir_wifi_ver/rt2860v2_ap" "$dir_wifi_dst/"
	fi
fi
if [ -n "$CONFIG_RT3090_AP" ] ; then
	dir_wifi_ver="2.7.X.X"
	if [ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "2.5" ] ; then
		dir_wifi_ver="2.5.X.X"
	fi
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/rt3090" "$dir_wifi_dst/"
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/rt3090_ap" "$dir_wifi_dst/"
fi
if [ -n "$CONFIG_RT5392_AP" ] ; then
	dir_wifi_ver="2.7.X.X"
	if [ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "2.5" ] ; then
		dir_wifi_ver="2.5.X.X"
	fi
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/rt5392" "$dir_wifi_dst/"
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/rt5392_ap" "$dir_wifi_dst/"
fi
if [ -n "$CONFIG_RT5592_AP" ] ; then
	dir_wifi_ver="2.7.X.X"
	if [ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "2.5" ] ; then
		dir_wifi_ver="2.5.X.X"
	fi
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/rt5592" "$dir_wifi_dst/"
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/rt5592_ap" "$dir_wifi_dst/"
fi
if [ -n "$CONFIG_RT3593_AP" ] ; then
	dir_wifi_ver="2.7.X.X"
	if [ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "2.5" ] ; then
		dir_wifi_ver="2.5.X.X"
	fi
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/rt3593" "$dir_wifi_dst/"
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/rt3593_ap" "$dir_wifi_dst/"
fi
if [ -n "$CONFIG_MT7610_AP" ] ; then
	dir_wifi_ver="3.0"
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7610" "$dir_wifi_dst/"
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7610_ap" "$dir_wifi_dst/"
fi
if [ -n "$CONFIG_MT76X2_AP" ] ; then
	dir_wifi_ver="3.0"
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt76x2" "$dir_wifi_dst/"
	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt76x2_ap" "$dir_wifi_dst/"
fi

# Continue with the original build script from the repository.
